#pragma once

#include "ISpellManager.hxx"

#define SPELL_NAVCOM_VIRUS 1
#define SPELL_NANOBOT_STREAM 2
#define SPELL_NANOBOT_SWARM 3
#define SPELL_MAGNETIC_DRAIN 4
#define SPELL_SIGNATURE_SPOOF 5
#define SPELL_PERFECT_DEFENSE 6
#define SPELL_KINETIC_BARRAGE_WEAK 7
#define SPELL_KINETIC_BARRAGE_STRONG 8
#define SPELL_LASER_BARRAGE_WEAK 9
#define SPELL_LASER_BARRAGE_STRONG 10
#define SPELL_MISSILE_SWARM_WEAK 11
#define SPELL_MISSILE_SWARM_STRONG 12
#define SPELL_HELLFIRE_RAIN 13
#define SPELL_MISSILE_MASSACRE 14
#define SPELL_WARPDRIVE_UPLINK 15

void add_all_spells(ISpellManager *);